apiVersion: v1
kind: Service
metadata:
  name: laravel-svc
  labels:
    app: laravel
spec:
  type: NodePort
  selector:
    app: laravel
  ports:
  - name: laravel-svc
    port: 80
    targetPort: 80