apiVersion: v1
kind: Service
metadata:
  name: nodejs-frontend-backend-svc
  labels:
    app: nodejs-frontend-backend
spec:
  type: NodePort
  selector:
    app: nodejs-frontend-backend
  ports:
  - name: nodejs-frontend-backend-svc
    port: 80
    targetPort: 80