apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-backend-1
spec:
  selector:
    matchLabels:
      app: nodejs-backend-1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs-backend-1
    spec:
      containers:
        - name: nodejs-backend-1
          image: XXXXXXXXXXXX.dkr.ecr.ap-south-1.amazonaws.com/nodejs-backend-1-prod
          envFrom:
            - configMapRef:
                name: backend-nodejs-backend-1-configmap
            - secretRef:
                name: nodejs-backend-1-secret
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000