apiVersion: v1
kind: Service
metadata:
  name: nodejs-frontend-backend-cors-svc
  labels:
    app: nodejs-frontend-backend-cors
spec:
  type: NodePort
  selector:
    app: nodejs-frontend-backend-cors
  ports:
  - name: nodejs-frontend-backend-cors-svc
    port: 80
    targetPort: 11001