apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-backend-2
spec:
  selector:
    matchLabels:
      app: nodejs-backend-2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs-backend-2
    spec:
      containers:
        - name: nodejs-backend-2
          image: XXXXXXXXXXXX.dkr.ecr.ap-south-1.amazonaws.com/nodejs-backend-2-prod
          envFrom:
            - configMapRef:
                name: backend-nodejs-backend-2-configmap
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000