apiVersion: v1
kind: Service
metadata:
  name: nodejs-backend-2-svc
  labels:
    app: nodejs-backend-2
spec:
  type: NodePort
  selector:
    app: nodejs-backend-2
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000