namespace: nodejs-backend-2
resources:
  - ../base/NodeJS Backend 2
  - ../base/mongodb
  - backend-nodejs-backend-2-ingress.yaml
  - backend-nodejs-backend-2-configmap.yaml
patchesStrategicMerge:
  - backend-nodejs-backend-2-deploy.yaml
images:
  - name: XXXXXXXXXXXX.dkr.ecr.ap-south-1.amazonaws.com/nodejs-backend-2-prod
    newTag: '8'