apiVersion: v1
kind: Service
metadata:
  name: nodejs-frontend-1-svc
  labels:
    app: nodejs-frontend-1
spec:
  type: NodePort
  selector:
    app: nodejs-frontend-1
  ports:
  - name: nodejs-frontend-1-svc
    port: 80
    targetPort: 80