apiVersion: v1
kind: Service
metadata:
  name: nodejs-frontend-2-svc
  labels:
    app: nodejs-frontend-2
spec:
  type: NodePort
  selector:
    app: nodejs-frontend-2
  ports:
  - name: nodejs-frontend-2-svc
    port: 80
    targetPort: 80