apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: url-shortner
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongo-pod
        image: mongo:6.0.7    
        ports:
        - containerPort: 27017
        resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              memory: "256Mi"
              cpu: "500m"
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
        volumeMounts:
          - name: mongodb-pv
            mountPath: /data/db
      volumes:
      - name: mongodb-pv
        persistentVolumeClaim:
          claimName: monogdb-pvc