apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: url-shortner
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: gp2
  hostPath:
    path: "/mnt/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monogdb-pvc
  namespace: url-shortner
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: gp2